apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nuodbs.nuodb.com
spec:
  preserveUnknownFields: false
  additionalPrinterColumns:
  - JSONPath: .status.adminHealth
    name: Admin
    type: string
  - JSONPath: .status.smHealth
    name: SM
    type: string
  - JSONPath: .status.teHealth
    name: TE
    type: string
  - JSONPath: .status.domainHealth
    name: Domain
    type: string
  - JSONPath: .status.phase
    name: Phase
    type: string
  - JSONPath: .status.controllerVersion
    name: ControllerVersion
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: nuodb.com
  names:
    categories:
    - nuodb
    kind: Nuodb
    listKind: NuodbList
    plural: nuodbs
    shortNames:
    - nuodb
    singular: nuodb
  scope: Namespaced
  validation:
    openAPIV3Schema:
      type: object
      description: "An instance of NuoDB, NuoDB Admin, and Transaction Engines."
      properties:
        spec:
          description: 'Spec defines the declared configuration of a NuoDB Instance and its components. For more information, see https://github.com/nuodb/nuodb-operator'
          properties:
            adminCount:
              description: 'The number of NuoDB Admin service pods. Requires one server available for each Admin Service. Example: adminCount: 1'
              format: int32
              type: integer
            adminStorageClass:
              description: 'The NuoDB Admin persistent storage class name. Example: adminStorageClass: glusterfs-storage'
              type: string
            adminStorageSize:
              description: 'The NuoDB Admin service log volume size (GB). Example: adminStorageSize: 5G'
              type: string
            apiServer:
              description: 'Load balancer service URL.  hostname:port (or LB address) for nuoadmin process to connect to. Example: apiServer: https://domain:8888'
              type: string
            container:
              description: 'The NuoDB fully qualified image name (FQIN) for the Docker image to use container: "registry.connect.redhat.com/nuodb/nuodb-ce:latest". Example: container: nuodb/nuodb-ce:latest'
              type: string
            dbAvailability:
              description: 'Availability requirement for this database. Options: "single-instance", "multiple-instance", "high-availability", "manual". Usage: "single-instance" - The operator manages a single instance of each NuoDB component (Admin, SM, TE).  In the event that one component goes down or becomes unavailable, the operator will automatically replace the failed component. This is the most resource friendly option for applications that can tolerate a brief outage.  "multiple-instance" - The operator manages multiple instances of each NuoDB component (Admin, SM, TE).  "high-availability" - The operator will maximize performance and reliability.  "manual" - The operator will enforce custom provided Admin, SM, TE instance counts.  The default is: "high-availability"'
              type: string
              enum:
              - single-instance
              - multiple-instance
              - high-availability
              - manual
            dbName:
              description: 'The NuoDB Database name. Must consist of lowercase alphanumeric characters ''[a-z0-9]+''.  Example: dbName: test'
              type: string
            dbPassword:
              description: 'dbPassword Database password.  Example: dbPassword: yourpasswordhere'
              type: string
            dbUser: 
              description: 'Name of Database user.  Example: dbUser: dba'
              type: string
            engineOptions:
              description: 'Additional NuoDB engine options. See http://doc.nuodb.com/Latest/Content/Database-Options.htm for a full list of options.  Example: engineOptions: "<Option> <Value> <Option> <Value> ..."'
              type: string
            insightsEnabled:
              description: 'Opt-In to hosted insights at https://insights.nuodb.com/. Set to false if opting-out in favor of insights local to the cluster.  Example: insightsEnabled: false'
              type: boolean
            smCount:
              description: 'Number of Storage Manager service pods. Requires 1 Storage Manager available  for each NuoDB Database.  Example: smCount: 1'
              format: int32
              type: integer
            smCpu:
              description: 'Storage Manager CPU cores to request.  Example: smCpu: 1'
              type: string
            smMemory:
              description: 'Storage Manager memory to request. Example: smMemory: 2Gi'
              type: string
            smStorageClass:
              description: 'Storage Manager persistent storage class name.  Example: smStorageClass: local-disk'
              type: string
            smStorageSize:
              description: 'Storage manager (SM) volume size (GB).  Example: smStorageSize: 20G'
              type: string
            storageMode:
              description: 'Run NuoDB using a persistent, local, disk volume "persistent" or volatile storage "ephemeral".  Must be set to one of those values.  Example: storageMode: persistent'
              type: string
              enum:
              - persistent
              - ephemeral
            teCount:
              description: 'The number of transaction engines (TE) nodes. Limited to three (3) in CE version of NuoDB.  Example: teCount: 1'
              format: int32
              type: integer
            teCpu:
              description: 'Transaction Engine (TE) CPU cores to request.  Example: teCpu: 1'
              type: string
            teMemory:
              description: 'Transaction Engine (TE) memory to request.  Example: teMemory: 2Gi'
              type: string
          required:
          - adminCount
          - adminStorageClass
          - adminStorageSize
          - apiServer
          - container
          - dbAvailability
          - dbName
          - dbPassword
          - dbUser
          - engineOptions
          - insightsEnabled
          - smCount
          - smCpu
          - smMemory
          - smStorageClass
          - smStorageSize
          - storageMode
          - teCount
          - teCpu
          - teMemory
          type: object
        status:
          description: 'The most recently observed status of a NuoDB instance in its components. For more information, see https://github.com/nuodb/nuodb-operator'
          type: object
          properties:
            adminHealth:
              description: AdminHealth of the NuoDB Domain
              type: string
            adminReadyCount:
              description: Admin Node Ready Count
              format: int32
              type: integer
            controllerVersion:
              description: ControllerVersion is the version of the controller that
                last updated the NuoDB Domain
              type: string
            domainHealth:
              description: DomainHealth of the NuoDB Domain
              type: string
            phase:
              description: Orchestration phase of the NuoDB Domain
              type: string
            smHealth:
              description: Storage Manager (SM) Health of the NuoDB Domain
              type: string
            smReadyCount:
              description: Storage Manager (SM) Node Ready Count
              format: int32
              type: integer
            teHealth:
              description: Transaction Engine (TE) Health of the NuoDB Domain
              type: string
            teReadyCount:
              description: Transaction Engine (TE) Node Ready Count
              format: int32
              type: integer
  version: v2alpha1
  versions:
  - name: v2alpha1
    served: true
    storage: true
